repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    - id: detect-secrets
      args: ['--baseline', '.secrets.baseline']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff-check
        types: [python]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types: [python]


  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        language_version: python3  # use the Python 3 interpreter pre-commit provides
        types: [python]
        stages: [pre-commit]